# Note : we are currently using this file with a machine already having rbenv and ruby-build installed
# every other required dependency, with the shell executor to deploy locally
# Yes, it deploys in development environment.

before_script:
  - id
  - ruby -v
  - which ruby
  - bundle install

# This step has to be manually triggered whenever you make a change to Gemfile
setup_env:
  when: manual
  tags:
    - projet-tracker-vm
  before_script:
    - ''
  script:
    - id
    - rbenv install -f 2.4.0
    - export PATH="$HOME/.rbenv/bin:$PATH"
    - rbenv init -
    - rbenv global 2.4.0
    - ruby -v
    - gem install bundler
    - rbenv rehash
    - bundle install
    - rbenv rehash

rspec:
  tags:
    - projet-tracker-vm
  script:
    - bundle exec rspec
