# Note : we are currently using this file with a machine already having rbenv and ruby-build installed
# every other required dependency, with the shell executor to deploy locally
# Yes, it deploys in development environment.

before_script:
  - id
  - ruby -v
  - which ruby
  - bundle install


setup_env:
  tags:
    - projet-tracker-vm
  before_script:
    - ''
  script:
    - id
    - rbenv install 2.4.0
    - export PATH="$HOME/.rbenv/bin:$PATH"
    - eval "$(rbenv init -)"

rspec:
  tags:
    - projet-tracker-vm
  script:
    - bundle exec rspec
